coverage:
  status:
    project:
      default:
        target: 95% # Set your desired coverage target
        threshold: 2% # Allow coverage to drop by 2% while still passing
    patch:
      default:
        target: 95% # Coverage target for new code

ignore:
  - src/tests/
  - src/constants/
  - src/types/
  - src/errors/
  - src/test/
  - src/config/

# Optional: Configure comment behavior on PRs
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false # If true, only post if coverage changes
  require_base: false # Must have a base coverage file
  require_head: true # Must have a head coverage file
