name: Production Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release and Deploy to Production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate GitHub App Token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: ${{ secrets.INSTALLATION_ID }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Run tests and generate coverage
        run: pnpm test:coverage

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: true

      - name: Build project
        run: pnpm build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ENVIRONMENT: "production"
          VITE_LOGGING_LEVEL: "error"

      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: pnpm release

      - name: Get new version
        id: get-version
        run: |
          version=$(jq -r '.version' package.json)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Extracted version: $version"
        if: steps.semantic.outputs.new_release_published == 'true'

      - name: Create build artifact
        run: |
          cd dist
          zip -r ../taskhub-production-v${{ steps.get-version.outputs.version }}.zip .
          cd ..
          echo "Build timestamp: $(date)" > build-info.txt
          echo "Version: ${{ steps.get-version.outputs.version }}" >> build-info.txt
          echo "Commit: ${{ github.sha }}" >> build-info.txt
          echo "Branch: main" >> build-info.txt
        if: steps.semantic.outputs.new_release_published == 'true'

      - name: Upload build artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: taskhub-production-v${{ steps.get-version.outputs.version }}
          path: |
            taskhub-production-v${{ steps.get-version.outputs.version }}.zip
            build-info.txt
          retention-days: 90
        if: steps.semantic.outputs.new_release_published == 'true'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        if: steps.semantic.outputs.new_release_published == 'true'

      - name: Make script executable
        run: chmod +x .github/scripts/upload-prod-artifact.sh
        if: steps.semantic.outputs.new_release_published == 'true'

      - name: Upload build to Azure Blob Storage
        id: upload_artifact
        run: |
          ./.github/scripts/upload-prod-artifact.sh \
            ${{ steps.get-version.outputs.version }} \
            ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            ${{ github.sha }}
        if: steps.semantic.outputs.new_release_published == 'true'

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: ""
          skip_app_build: true
        if: steps.semantic.outputs.new_release_published == 'true'

      - name: Post deployment notification
        if: steps.semantic.outputs.new_release_published == 'true' && success()
        run: |
          echo "🚀 Successfully deployed to production"
          echo "URL: https://witty-mushroom-0ba06a800.6.azurestaticapps.net"
          echo "Build artifact: taskhub-production-${{ steps.timestamp.outputs.timestamp }}.zip stored in Azure Blob Storage"
          echo "Download link: ${{ steps.upload_artifact.outputs.download_url }}"
