name: Production Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release and Deploy to Production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate GitHub App Token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: ${{ secrets.INSTALLATION_ID }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm test || echo "No tests implemented yet"

      - name: Build project
        run: pnpm build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ENVIRONMENT: "production"
          VITE_LOGGING_LEVEL: "error"

      - name: Get build timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create build artifact
        run: |
          TIMESTAMP=${{ steps.timestamp.outputs.timestamp }}
          cd dist
          zip -r ../taskhub-prod-$TIMESTAMP.zip .
          cd ..
          echo "Build timestamp: $(date)" > build-info.txt
          echo "Environment: production" >> build-info.txt
          echo "Commit: ${{ github.sha }}" >> build-info.txt
          echo "Branch: main" >> build-info.txt

      - name: Upload build artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: taskhub-prod
          path: |
            taskhub-prod-*.zip
            build-info.txt
          retention-days: 90

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Make script executable
        run: chmod +x .github/scripts/upload-prod-artifact.sh

      - name: Upload build to Azure Blob Storage
        id: upload_artifact
        run: |
          ./.github/scripts/upload-prod-artifact.sh \
            production \
            ${{ steps.timestamp.outputs.timestamp }} \
            ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            ${{ github.sha }}

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: ""
          skip_app_build: true

      - name: Post deployment notification
        if: success()
        run: |
          echo "🚀 Successfully deployed to production"
          echo "URL: https://witty-mushroom-0ba06a800.6.azurestaticapps.net"
          echo "Build artifact: taskhub-prod-${{ steps.timestamp.outputs.timestamp }}.zip stored in Azure Blob Storage"
          echo "Download link: ${{ steps.upload_artifact.outputs.download_url }}"
